version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_PATH=/app/data/ssai_aidea_prod.db
    volumes:
      - ./data:/app/data  # 데이터베이스 파일을 호스트에 저장
    restart: unless-stopped

  # frontend는 backend에서 서빙되므로 별도 컨테이너 불필요
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped